---
title: "Model Selection"
author: "Chen Mo"
date: "12/14/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(corrplot)
library(HH)
library(olsrr)
library(leaps)
```

## Data Cleaning
```{r}
#drop missing values from data set#
crime_df = read.csv("./data/HateCrimes.csv") %>%
 rename("income" = "median_household_income",
         "degree" = "perc_population_with_high_school_degree",
         "noncitizen" = "perc_non_citizen",
         "nonwhite" = "perc_non_white",
         "hc_rate" = "hate_crimes_per_100k_splc") %>%
  mutate(income = as.numeric(income),
         degree = as.numeric(degree),
         noncitizen = as.numeric(noncitizen),
         nonwhite = as.numeric(nonwhite),
         hc_rate = as.numeric(hc_rate),
         gini_index = as.numeric(gini_index),
         unemployment = as.factor(unemployment),
         urbanization = as.factor(urbanization)) %>%
  drop_na() %>%
  dplyr::select(-state)
```

## Outlier
```{r}
#drop outlier#  
crime_df = crime_df[-9,] 
```

## Descriptive Analysis
```{r}
plot = ggplot(aes(x = hc_rate), data = crime_df) + geom_histogram() + geom_density() + labs(x = "hate crime rate", title = "distribution of hate crime rate")
plot
#Since the distribution of hate crime rate is right-skewed, we think there might need potential transformation
```

## Model Transformation 
```{r}
fit_full_original = lm(data = crime_df, hc_rate ~ .)

#box-cox for full model without transformation
fit_full_original %>% 
  MASS::boxcox() 
#From box-cox plot, we think there needs log transformation.

#Take transformation#  
crime_log = 
  crime_df %>%
  mutate(hc_rate = log(hc_rate))

fit_full_log = lm(data = crime_log, hc_rate ~ .)
#QQ plot for model with transformation and without transformation
qqnorm(resid(fit_full_log), xlab = "Expected Value", ylab = "Residual", main = "")
qqline(resid(fit_full_log))
title("QQ Plot for Ln(Hate Rate)")

qqnorm(resid(fit_full_original), xlab = "Expected Value", ylab = "Residual", main = "")
qqline(resid(fit_full_original))
title("QQ Plot for Hate Rate")
#From two QQ-plots, we think log transformation is better
```

#FiveThirtyEight#
```{r}
fit_fivethirtyeight = lm(data = crime_df, hc_rate ~ gini_index + degree)
summary(fit_fivethirtyeight)
#Further analysis will be explained after we select our final model
```

#Model Selection#
```{r}
#Test for collinearity
pairs(crime_df)

corr_data = 
  cor(cbind(hc_rate = pull(crime_log, hc_rate),
        model.matrix(hc_rate~., data = crime_df)[,-1])
  )

corr_data %>% 
  corrplot(method = "color", addCoef.col = "black", tl.col = "black", tl.srt = 45, insig = "blank" , number.cex = 0.7, diag = FALSE)
#We can find some of the predictors might have collinearity issues. We use VIF method to verify.

vif(fit_full_log) #None of VIF exceeds 5, meaning none of the predictors are highly correlated with each other.

#Stepwise Selection
#Backward
step(fit_full_log, direction = 'backward')
#lm(formula = hc_rate ~ degree + gini_index, data = crime_log)

#Forward
step(fit_full_log, direction = 'forward')
#lm(formula = hc_rate ~ unemployment + urbanization + income + 
#   degree + noncitizen + gini_index + nonwhite

#Both
step(fit_full_log, direction = 'both')
#lm(formula = hc_rate ~ degree + gini_index, data = crime_log)

#Based on the stepwise outcome, 2 models are selected(one uses degree and gini_index as predictors, the other uses the full model). We select our model based on these two models.

summary(fit_full_log)
#Based on the regression output of full model, we find that unemployment is the third significant predictor apart from gini_index and degree. Thus, we consider unemployment as the interation term. 
#Plot to check interaction
crime_log %>%
  mutate(
    unemployment = as.factor(unemployment) ) %>% 
  ggplot(aes(x = gini_index, y = hc_rate, color = unemployment)) + 
  geom_point() +
  stat_smooth(method = "lm") 
#From the plot above, we find the interaction between gini_index and unemployment needed to be considered.

#ANOVA test
fit_1 = lm(hc_rate ~ degree + gini_index*unemployment, data = crime_log)
fit_2 = lm(hc_rate ~ degree + gini_index, data = crime_log)#We also use ANOVA test to test the model with and without the interaction term.
summary(fit_1)
summary(fit_2)
anova(fit_2, fit_1)
#From the test, p-value is 0.1296. Besides, if we contain the interaction term in the model, the adjusted R-square also increases from 0.1185 to 0.1654 which exceeds 6% increase. We choose this model as the third model to do the final comparison

#Comparison between models
crime_log %>% 
  nest(data = c(unemployment, urbanization, income, degree, noncitizen, gini_index, 
    nonwhite, hc_rate)) %>%
  mutate(
    model1 = map(.x = data, ~lm(hc_rate ~ degree + gini_index, data = .x)),
    model2 = map(.x = data, ~lm(hc_rate ~ degree + gini_index*unemployment, data = .x)),
    model3 = map(.x = data, ~lm(hc_rate ~ unemployment + urbanization + income + degree + noncitizen + gini_index + nonwhite, data = .x))) %>%
  pivot_longer(
    model1:model3,
    names_to = "model",
    values_to = "results"
  ) %>% 
  mutate(
    AIC = map(.x = results, ~AIC(.x)),
    Cp = map(.x = results, ~ols_mallows_cp(.x, fit_full_log)),
    adj_r_sq = map(.x = results, ~summary(.x)$adj.r.squared)
  ) %>% 
  unnest(AIC:adj_r_sq) %>%
  mutate(num_parameter = c(3,5,8)) %>% 
  dplyr::select(model, AIC, Cp, adj_r_sq, num_parameter) %>% 
  knitr::kable(digits = 3)
#Cp of all models are smaller or equal to the number of parameters. So, all models are good
#adjusted R^2 of model2 is the largest
#AIC of model2 is the smallest, indicating model2 is the best
#So, based on the different types of consideration above, model2 is the best#

#QQ plot of the model with interaction term 
qqnorm(resid(fit_1), xlab = "Expected Value", ylab = "Residual", main = "")
qqline(resid(fit_1))
title("QQ Plot for Ln(Hate Rate) with interation term")
#From the QQ-plot, we think the model containing degree, gini_index, unemployment, and interaction term between gini_index and unemployment is a good fit since residuals of this model follows normal distribution.

#Stratified Method
crime_lowunemployment = crime_log %>% 
  filter(unemployment == "low")
crime_highunemployment = crime_log %>% 
  filter(unemployment == "high")
fit_3 = lm(hc_rate ~ degree + gini_index, data = crime_lowunemployment)
fit_4 = lm(hc_rate ~ degree + gini_index, data = crime_highunemployment)
summary(fit_3)
summary(fit_4)
#After stratification, the coefficients of gini_index have different directionality, which means the associations between hc_rate and gini_index have opposite directions for the two groups even though neither is significant. 

#Compared with the model of FiveThirtyEight, as the regression outputs of our stratified models shown above, for people with low level of state unemployment, gini_index is significant and with positive direction, but for people with high level of state unemployment, gini_index is not significant and with negative direction. 
#For the other covariates, as for unemployment, the association between hate crime rate and gini_index varies between different unemployment group. 
#As for degree, we can see that degree is significant. 
#All the other covariates we think are not significant and should not be considered into the model.

#CI for stratified model
confint(fit_3, level = 0.95)
confint(fit_4, level = 0.95)#先考虑看写不写
```


